### ISSUE TITLE
MVP: Add support for Base chains

### ISSUE THREAD

**Issue by michalsmiarowski** [threshold-network/bitcoin-on-base#14]
~We should reflecct the changes from https://github.com/threshold-network/token-dashboard/pull/605.~

The MVP dApp must be able to interact with Base chains (mainnet, Sepolia and Goerli). If possible, the support for Ethereum chains should be removed from the codebase.
```[tasklist]
### Tasks
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/42
- [ ] https://github.com/threshold-network/bitcoin-on-base/pull/39
```

**Comment by lukasz-zimnoch** [comment]
Just keep in mind this should be Base Sepolia.

**Comment by lukasz-zimnoch** [comment]
The work remaining here is basically part of https://github.com/threshold-network/bitcoin-on-base/issues/6
