### ISSUE TITLE
MVP: Connect wallet action

### ISSUE THREAD

**Issue by lukasz-zimnoch** [threshold-network/bitcoin-on-base#3]
This task is about implementing a **Connect wallet** button allowing to connect a Base-compatible Web3 wallet. This button should be placed in the top-right corner of the initial page. After the wallet is connected, user's Base address should be displayed instead. 

Moreover, if the wallet is not connected, the bridging form should also display a call to action with a **Connect wallet** button available nearby. Once the wallet is connected, the user's Base address should be used to fill the appropriate **Base Address** field in the form.

**Comment by kpyszkowski** [comment]
This issue has been resolved with PR #13 
It can be closed @lukasz-zimnoch
